// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBez4vA8aeBDyeOBL0ql3qwsJy2LBwEvxI',
    appId: '1:513278837130:web:7a0a2093a54e4603e90873',
    messagingSenderId: '513278837130',
    projectId: 'taste-of-africa-ffb16',
    authDomain: 'taste-of-africa-ffb16.firebaseapp.com',
    storageBucket: 'taste-of-africa-ffb16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRU8ZRB7ZJGWIYKnLLFrUQhkoCOrQYlmA',
    appId: '1:513278837130:android:0b1a2b4495cc4ff1e90873',
    messagingSenderId: '513278837130',
    projectId: 'taste-of-africa-ffb16',
    storageBucket: 'taste-of-africa-ffb16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMtbk7TakXoXetrN6YTaECouv6qr-r83w',
    appId: '1:513278837130:ios:477c4dc08362fe01e90873',
    messagingSenderId: '513278837130',
    projectId: 'taste-of-africa-ffb16',
    storageBucket: 'taste-of-africa-ffb16.appspot.com',
    iosClientId: '513278837130-t55hg41m9cmiphfpcu9mjtn2qvln57bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMtbk7TakXoXetrN6YTaECouv6qr-r83w',
    appId: '1:513278837130:ios:477c4dc08362fe01e90873',
    messagingSenderId: '513278837130',
    projectId: 'taste-of-africa-ffb16',
    storageBucket: 'taste-of-africa-ffb16.appspot.com',
    iosClientId: '513278837130-t55hg41m9cmiphfpcu9mjtn2qvln57bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
